/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ametro_jni_Natives */

#ifndef _Included_org_ametro_jni_Natives
#define _Included_org_ametro_jni_Natives
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ametro_jni_Natives
 * Method:    SplitCsvString
 * Signature: (Ljava/lang/String;C)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_ametro_jni_Natives_SplitCsvString
  (JNIEnv *, jclass, jstring, jchar);

/*
 * Class:     org_ametro_jni_Natives
 * Method:    getVisibleRenderElements
 * Signature: ([Lorg/ametro/render/RenderElement;[Landroid/graphics/RectF;I)[Lorg/ametro/render/RenderElement;
 */
JNIEXPORT jobjectArray JNICALL Java_org_ametro_jni_Natives_getVisibleRenderElements
  (JNIEnv *, jclass, jobjectArray, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
